<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\JevBrowse.Domain\JevBrowse.Domain.csproj" />
    <ProjectReference Include="..\JevBrowse.Renderer.Abstractions\JevBrowse.Renderer.Abstractions.csproj" />
    <ProjectReference Include="..\JevBrowse.ResourceOS\JevBrowse.ResourceOS.csproj" />
    <ProjectReference Include="..\JevBrowse.Storage\JevBrowse.Storage.csproj" />
    <ProjectReference Include="..\JevBrowse.TrustOS\JevBrowse.TrustOS.csproj" />
  </ItemGroup>
</Project>
